name: payhere_mobilesdk_flutter
description: Make PayHere payments with your Flutter App!
version: 1.0.5
homepage: https://github.com/PayHereLK/payhere-mobilesdk-flutter
publish_to: none

environment:
  # sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  payhere_platform_interface: 
    path: ../payhere_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: lk.payhere
        pluginClass: PayhereMobilesdkFlutterPlugin
      ios:
        pluginClass: PayhereMobilesdkFlutterPlugin